### ISSUE TITLE
Greedy Algorithm + Beds = Stuck Workers

### ISSUE THREAD

**Issue by strigona** [redblobgames/2327-roguelikedev#1]
I know the sleepiness isn't implemented, but just wanted to identify that once a worker goes to a bed, the worker get stuck on beds because it's the closest job.

I love the concept and hope more functionality & gameplay is added!

**Comment by redblobgames** [comment]
I agree, the beds are broken right now. My plans were to implement one of:

1. The *furniture* has a cooldown before it can be used again. I thought this would especially be useful on fields of crops, as they would have to wait before they could be harvested again.
2. The *colonist* has a cooldown before they are hungry or sleepy again. I think this is the most logical thing.
3. The *world* has a schedule where all colonists become hungry or sleepy at certain times of day. I think this might be the most fun to watch, since everyone will want to eat or sleep around the same time.

**Comment by redblobgames** [comment]
Ok, I've implemented #3. The colonists will get sleepy at night. They'll use the beds. That will clear their sleepy status. Then they won't use the beds right away, but instead look for other jobs.

**Comment by strigona** [comment]
Cool! That's much more fun to play! It reminds me of a super early/primitive Prison Architect
